# Exercise 

In this exercise, you will have to do the following tasks

1) Write metadata for the datasets:
    a, b, and c ...
2) Translate the SKS codes of df[col] into ICD-10 codes and add the codes as a additional column. 
4) Identify if these datasets have some biases
5) Identify danish registries where similar data can be found for data a, b, and c ....

In [1]:
import pandas as pd

In [5]:
baseline_data = pd.read_csv("Data/baseline_data.csv")
blood_data = pd.read_csv("Data/blood_data.csv")
diag_data = pd.read_csv("Data/diag_data.csv")
dict_data = pd.read_csv("Data/dict_data.csv")
events = pd.read_csv("Data/events.csv")
quest_data = pd.read_csv("Data/quest_data.csv")
snomed_data = pd.read_csv("Data/snomed_data.csv")
treat_data = pd.read_csv("Data/treat_data.csv")
visit_date = pd.read_csv("Data/visit_date.csv")

In [4]:
baseline_data

       id     sex     d.birth  smoking
0       2  female  1941-07-14   former
1       3    male  1931-10-02   former
2       4    male  1944-11-22    never
3       5  female  1939-04-13  current
4       6    male  1962-04-18  current
..    ...     ...         ...      ...
737  1592  female  1942-04-06  current
738  1593    male  1950-02-08  current
739  1594  female  1928-12-07    never
740  1595    male  1942-08-27  current
741  1596  female  1936-04-05   former

[742 rows x 4 columns]

In [8]:
dict_data

   Unnamed: 0            diag    code
0           1        diabetes    DE10
1           2    hypertension  BZFC8A
2           3  hyperlipidemia   DE782

In [9]:
events

     Unnamed: 0    id        date              event   type
0             1     2  2010-05-07         malignancy  other
1             2     2  2011-11-07        other death  death
2             3     5  2008-03-31  revascularization  minor
3             4     6  2006-07-18  revascularization  minor
4             5     6  2006-09-19  revascularization  minor
..          ...   ...         ...                ...    ...
704         705  1568  2008-09-27             stroke  major
705         706  1568  2008-11-14  revascularization  minor
706         707  1592  2007-01-22  revascularization  minor
707         708  1592  2007-01-23  revascularization  minor
708         709  1596  2006-02-28        other death  death

[709 rows x 5 columns]

In [10]:
quest_data

      Unnamed: 0    id      date.x  anxiety  sleep  alcohol  fruit  vegetable
0              1     2  2005-04-03        3      3        1    3.0          3
1              2     2  2006-09-16        4      3        1    3.0          3
2              3     2  2007-08-07        3      1        1    4.0          3
3              4     2  2008-12-11        2      2        1    4.0          4
4              5     2  2009-12-20        2      4        1    4.0          3
...          ...   ...         ...      ...    ...      ...    ...        ...
3892        3893  1592  2007-05-23        2      2        1    NaN          3
3893        3894  1593  2005-11-08        2      1        3    4.0          4
3894        3895  1594  2005-08-14        2      3        1    4.0          4
3895        3896  1595  2005-08-18        2      3        2    2.0          4
3896        3897  1596  2005-10-13        3      4        1    4.0          4

[3897 rows x 8 columns]